(in-package #:od-icfpc2016)

(defun rotate-point (point segment)
  (let* ((points (coerce segment 'list))
        (delta (apply #'point- points))
        (dx (mapcar #'car delta))
        (dy (mapcar #'cdr delta))
        (dx2 (* dx dx))
        (dy2 (* dy dy))
        (d (+ dx2 dy2))
        (a (/ (- dx2 dy2) d))
        (b (/ (* 2 dx dy) d))
        (x (car point))
        (y (cadr point))
        (x0 (- x (caar points)))
        (y0 (- y (caadr points))) )
   (list (+ (* a x0) (* b y0) (caar points)) (+ (* -1 a y0) (* b x0) (caadr points)))))
